### ISSUE TITLE
Missing .java file

### ISSUE THREAD

**Issue by SAC-CS** [SACCS112TranT/hello-world#2]
Please submit source code.

**Comment by SACCS112TranT** [comment]
public class HelloSAC {
	public static void main(String[] args) {
	      // Prints "Hello, World" in the terminal window.
	      System.out.println("Hello, SAC");
	}
}

**Comment by SAC-CS** [comment]
// There's some more work to do here to get the .java file up here...but I will take this for now.
// Next step is to integrate GitHub with IDE.
